name: Build Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.platform }} Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [pi1, pi2, pi3, pi4, pi5]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Make build script executable
        run: chmod +x scripts/build_image.sh

      - name: Build image for ${{ matrix.platform }}
        run: |
          ./scripts/build_image.sh --platform ${{ matrix.platform }}